name: ticklemickle_m
description: "A new financial community service."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^13.1.0
  url_strategy: ^0.3.0
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  share_plus: ^10.1.4
  provider: ^6.1.2
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.10
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon3D/
    - assets/chatbot/question/
    - assets/chatbot/result/lookalike/
    - assets/chatbot/result/common/
    - assets/chatbot/result/logo/

flutter_launcher_name:
  name: "티끌미끌"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_white.png"
