// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRIBd9psXYkYFL9-z4rs-Us_cJkTW3I_M',
    appId: '1:416243924439:web:a60dc4c6990852872b1f92',
    messagingSenderId: '416243924439',
    projectId: 'ticklemickle-m',
    authDomain: 'ticklemickle-m.firebaseapp.com',
    storageBucket: 'ticklemickle-m.firebasestorage.app',
    measurementId: 'G-EXXDFHC07L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3Cx2sGERq9mAk29o1fRYfoXrYCTL4Mo',
    appId: '1:416243924439:android:e8604d53630b7f152b1f92',
    messagingSenderId: '416243924439',
    projectId: 'ticklemickle-m',
    storageBucket: 'ticklemickle-m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlQX2t15wqS4d7Xa_5hsKKTCVCpIV8ceg',
    appId: '1:416243924439:ios:2741b20d3faa6d542b1f92',
    messagingSenderId: '416243924439',
    projectId: 'ticklemickle-m',
    storageBucket: 'ticklemickle-m.firebasestorage.app',
    iosBundleId: 'com.example.ticklemicklem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlQX2t15wqS4d7Xa_5hsKKTCVCpIV8ceg',
    appId: '1:416243924439:ios:2741b20d3faa6d542b1f92',
    messagingSenderId: '416243924439',
    projectId: 'ticklemickle-m',
    storageBucket: 'ticklemickle-m.firebasestorage.app',
    iosBundleId: 'com.example.ticklemicklem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRIBd9psXYkYFL9-z4rs-Us_cJkTW3I_M',
    appId: '1:416243924439:web:2908d4a2dc4285a82b1f92',
    messagingSenderId: '416243924439',
    projectId: 'ticklemickle-m',
    authDomain: 'ticklemickle-m.firebaseapp.com',
    storageBucket: 'ticklemickle-m.firebasestorage.app',
    measurementId: 'G-DWPLXS7HZ3',
  );
}
